server:
  port: 5221
  servlet:
    context-path: /api

spring:
  application:
    name: stone
    version: 0.0.1-SNAPSHOT

mybatis-flex:
  mapper-locations: classpath*:/mapper/**/*.xml
  executor-type: REUSE
  global-config:
    print-banner: false
    key-config:
      before: true
      key-type: Generator
      value: flexId
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
  default-datasource-key: master
  datasource:
    master:
      driver-class-name: org.sqlite.JDBC
      url: jdbc:sqlite:db/tone.db
      type: com.zaxxer.hikari.HikariDataSource
      minimum-idle: 10
      maximum-pool-size: 50
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 60000
      max-lifetime: 1800000
      keepalive-time: 30000
      connection-test-query: SELECT 1
      auto-commit: true
      pool-name: tone-pool

tone:
  captcha:
    type: Line
    width: 200
    height: 100
    length: 5
    stain: 0
  jwt:
    issuer: FTone
    secret: qwertyuiopasdfghjklzxcvbnm1234567890+-*/=
    offset: 120
    leeway: 5